language: node_js
node_js:
  - "10.15.3"
script:
  - npm install
  - CI=false npm run build
  - cd functions && npm install
  - cd ..
deploy:
  cleanup: false
  provider: firebase
  token: $FIREBASE_TOKEN
  project: final-project-v2-d6704
